=== Rugeno/CollegeProject/catalog_20049041.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="a">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="href" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Logo" type="xs:string"/>
  <xs:element name="li">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="a"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ul">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Logo"/>
        <xs:element ref="li" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="navbar">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ul"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="StoreName">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="storeID"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Key-Feature" type="xs:string"/>
  <xs:element name="Type" type="xs:string"/>
  <xs:element name="Refundable" type="xs:string"/>
  <xs:element name="Validity" type="xs:string"/>
  <xs:element name="NoOfUsers" type="xs:float"/>
  <xs:element name="DiscountVouchers" type="xs:string"/>
  <xs:element name="Platform" type="xs:string"/>
  <xs:element name="Key-Features">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Key-Feature" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GiftCardName">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="Language" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Description" type="xs:string"/>
  <xs:element name="Image">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:byte" name="imageNumber" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Bodi">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element ref="Type"/>
        <xs:element ref="Refundable"/>
        <xs:element ref="Validity"/>
        <xs:element ref="NoOfUsers"/>
        <xs:element ref="DiscountVouchers"/>
        <xs:element ref="Platform"/>
        <xs:element ref="Key-Features"/>
        <xs:element ref="Availability"/>
        <xs:element ref="ExclusiveDeal"/>
        <xs:element ref="CashBack"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="GiftCard">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element ref="GiftCardName"/>
        <xs:element ref="Description"/>
        <xs:element ref="Image"/>
        <xs:element ref="Bodi">
          <xs:annotation>
            <xs:documentation>stores image of the GiftCard</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:choice>
      <xs:attribute type="xs:byte" name="giftcardNumber" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Availability" type="xs:string"/>
  <xs:element name="ExclusiveDeal" type="xs:string"/>
  <xs:element name="CashBack" type="xs:string"/>
  <xs:element name="float-Child">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="GiftCard"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="float-Child1">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="GiftCard"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Store">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="navbar">
          <xs:annotation>
            <xs:documentation>Creating child element for storing store details</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="StoreName"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GiftCards">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element ref="float-Child">
          <xs:annotation>
            <xs:documentation>Creating child element for storing GiftCard details</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="float-Child1"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element type="xs:string" name="Address" />
  <xs:element type="xs:int" name="TelephoneNumber"/>
  <xs:element type="xs:anyURI" name="Website"/>
  <xs:element name="GiftCardStore">
    <xs:annotation>
      <xs:documentation>Linking external CSS file to XML file</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Store">
          <xs:annotation>
            <xs:documentation>Creating root element and linking external schema</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="GiftCards"/>
        <xs:element ref="Address"/>
        <xs:element ref="TelephoneNumber"/>
        <xs:element ref="Website"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Rugeno/CollegeProject/catalog_20049041.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/css" href="catalog_20049041.css"?><!--Linking external CSS file to XML file-->
<GiftCardStore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_20049041.xsd"> <!--Creating root element and linking external schema-->
    <Store> <!--Creating child element for storing store details-->
        <navbar>
            <ul>
                <Logo></Logo>
                <li><a href="#Home">Home</a></li>
                <li><a href="#Offer">Offer</a></li>
                <li><a href="#Login">Login</a></li>
                <li><a href="#Cart">Cart</a></li>
                <li><a href="#Contact">Contact</a></li>
            </ul>
        </navbar>
        <StoreName storeID="S13356"> Gift Card Store </StoreName>
        
    </Store>
    
    <GiftCards> <!--Creating child element for storing GiftCard details-->
    <float-Child>
        <GiftCard giftcardNumber = "1">
            <GiftCardName>VALORANT $50 Gift Card</GiftCardName>
            <Description> Riot Gift Cards are the most reliable way to buy in-game currency 
            where you don't even need a credit/debit card. Riot Gift Card codes can be received digitally 
            via e-mail, or they can be activated by entering the pin code, which will be instantly reflected 
            in your account. 
            </Description>
            <Image imageNumber = "1"/> <!--stores image of the GiftCard-->
            <Bodi>
            <Type>Key</Type>
            <Refundable> Before 7 days of Purchace </Refundable>
            <Validity> No expiration date</Validity>
            <NoOfUsers>427 </NoOfUsers>
            <DiscountVouchers>N/A</DiscountVouchers>
            <Platform> Riot Games</Platform>
            <Key-Features>
            <Key-Feature>Delivered digitally soon after your purchase </Key-Feature>
            <Key-Feature>Shipped by SJKGiftCardStore.com</Key-Feature>
            </Key-Features>
            </Bodi>
        </GiftCard> 
    </float-Child>

    <float-Child1>
        <GiftCard giftcardNumber = "2">
            <GiftCardName>Valorant 10$ Gift Card</GiftCardName>
            <Description> Riot Gift Cards are the most reliable way to buy in-game currency 
            where you don't even need a credit/debit card. Riot Gift Card codes can be received digitally 
            via e-mail, or they can be activated by entering the pin code, which will be instantly reflected 
            in your account.</Description>
            <Image imageNumber = "2"/>
            <Bodi>
            <Type>Key </Type>
            <Validity>No expiration date</Validity>
            <NoOfUsers> 34550</NoOfUsers>
            <DiscountVouchers> N/A </DiscountVouchers>
            <Availability> In Stock</Availability>
            <Refundable>Before 7 days of purchase </Refundable>
            <Platform>Riot Games </Platform>
            <Key-Features>
            <Key-Feature> Delivered digitally soon after your purchase</Key-Feature>
            </Key-Features>
            </Bodi>
        </GiftCard>
    </float-Child1>

    <float-Child>
        <GiftCard giftcardNumber = "3">
            <GiftCardName >Steam 20$ Gift Card </GiftCardName>
            <Description> If you love good cheap games, then this is the offer for you! We offer products that are worth much more than the ExclusiveDeal paid!
            This product gives 5 unique CD-keys which can be activated on Steam platform.</Description>
            <Image imageNumber= "3"/>
            <Bodi>
            <Type > Key </Type>
            <Validity> No expiration date</Validity>
            <NoOfUsers>23344 </NoOfUsers>
            <DiscountVouchers>N/A </DiscountVouchers>
            <Availability>In Stock </Availability>
            <ExclusiveDeal> [Limited]</ExclusiveDeal>
            <Refundable> Before 10 days of purchase</Refundable>
            <Platform>Steam</Platform>
            <Key-Features>
            <Key-Feature> Delivered digitally soon after your purchase</Key-Feature>
            <Key-Feature>Key provided via email</Key-Feature>
            </Key-Features>
            </Bodi>
        </GiftCard>
    </float-Child>

        <float-Child1>
        <GiftCard giftcardNumber = "4">
            <Image imageNumber = "4"/>
            <GiftCardName>Steam 50$ Gift card</GiftCardName>
            <Description>If you love good cheap games, then this is the offer for you! We offer products that are worth much more than the ExclusiveDeal paid!
            This product gives 5 unique CD-keys which can be activated on Steam platform.</Description>
            <Bodi>
            <Type>Key</Type>
            <Validity>No expiration date</Validity>
            <NoOfUsers>40000 </NoOfUsers>
            <DiscountVouchers>N/A </DiscountVouchers>
            <Availability>In Stock</Availability>
            <ExclusiveDeal>[Limited]</ExclusiveDeal>
            <Refundable> Before 10 days of purchase</Refundable>
            <Platform>Steam</Platform>
            <Key-Features>
            <Key-Feature>Delivered digitally soon after your purchase</Key-Feature>
            <Key-Feature>Key provided via email</Key-Feature>
            <Key-Feature>Supplied by SJKGiftCardStore.com</Key-Feature>
            </Key-Features>
            </Bodi>
        </GiftCard>
        </float-Child1>

        <float-Child>
         <GiftCard giftcardNumber = "5">
            <Image imageNumber= "5"/>
            <GiftCardName Language="Nepali">Apple 500$ Gift Card</GiftCardName>
            <Description>Apple gift cards are one of the most popular gift card purchases right now because of how easy and convenient 
            they are to purchase Apple products, accessories, apps, iCloud storage space and any other Apple service. 
            Instant delivery upon purchase allows you to email Apple gift cards to anyone you'd like.  
            After a quick and simple checkout process, you will instantly receive an emailed Apple gift card.</Description>
            <Bodi>
            <Type >Key</Type>
            <Validity>Upto 6 months of purchase</Validity>
            <NoOfUsers>411000 </NoOfUsers>
            <DiscountVouchers>N/A </DiscountVouchers>
            <Availability>In Stock </Availability>
            <Refundable> No</Refundable>
            <Platform>Apple Inc.</Platform>
            <CashBack>5% CashBack</CashBack>
            </Bodi>
        </GiftCard>
        </float-Child>

        <float-Child1>
         <GiftCard giftcardNumber = "6">
            <Image imageNumber= "6"/>
            <GiftCardName >Apple 50$ Gift Card</GiftCardName>
            <Description>Apple gift cards are one of the most popular gift card purchases right now because of how easy and convenient 
            they are to purchase Apple products, accessories, apps, iCloud storage space and any other Apple service. 
            Instant delivery upon purchase allows you to email Apple gift cards to anyone you'd like.  
            After a quick and simple checkout process, you will instantly receive an emailed Apple gift card.</Description>
            <Bodi>
            <Type > Key </Type>
            <Validity>Upto 6 months of purchase</Validity>
            <NoOfUsers>451000</NoOfUsers>
            <DiscountVouchers>Rock</DiscountVouchers>
            <Availability>In Stock </Availability>
            <Refundable> No</Refundable>
            <Platform>Apple Inc.</Platform>
            <Key-Features>
            <Key-Feature>Card delivered via email</Key-Feature>
            </Key-Features>
            </Bodi>
        </GiftCard>
        </float-Child1>

        <float-Child>
         <GiftCard giftcardNumber = "7">
            <Image imageNumber= "7"/>
            <GiftCardName Language="English">GooglePlay 100$ Gift Card</GiftCardName>
            <Description>Google Play Gift Card is the prepaid top-up card for Google Play Balance. It can be redeemed to pay for thousands of books, songs, movies, apps, magazines and many more on Google Play store. 
            Use a Google Play gift code to go further in your favorite games like Clash Royale or Pokemon Go or redeem your code for the latest apps, movies, music, books, and more. 
            There’s no credit card required, and balances never expire. Treat yourself or give the gift of Play today.</Description>
            <Bodi>
            <Type >Key</Type>
            <Validity>No expiration date</Validity>
            <NoOfUsers>11446 </NoOfUsers>
            <DiscountVouchers>N/A</DiscountVouchers>
            <Availability> In Stock</Availability>
            <Refundable>No</Refundable>
            <Platform>Google</Platform>
            <CashBack>2% CashBack </CashBack>
            </Bodi>
        </GiftCard> 
        </float-Child> 

        <float-Child1>
         <GiftCard giftcardNumber = "8">
            <Image imageNumber= "8"/>
            <GiftCardName Language="English">GooglePlay 10$ Gift Card</GiftCardName>
             <Description>Google Play Gift Card is the prepaid top-up card for Google Play Balance. It can be redeemed to pay for thousands of books, songs, movies, apps, magazines and many more on Google Play store. 
            Use a Google Play gift code to go further in your favorite games like Clash Royale or Pokemon Go or redeem your code for the latest apps, movies, music, books, and more. 
            There’s no credit card required, and balances never expire. Treat yourself or give the gift of Play today.</Description>
             <Bodi>
            <Type >Key</Type>
            <Validity>No expiration date</Validity>
            <NoOfUsers>42000 </NoOfUsers>
            <DiscountVouchers>N/A</DiscountVouchers>
